// dart format width=80
// GENERATED BY drift_dev, DO NOT MODIFY.
// ignore_for_file: type=lint,unused_import
//
import 'package:drift/drift.dart';

class RecurringPayments extends Table
    with TableInfo<RecurringPayments, RecurringPaymentsData> {
  @override
  final GeneratedDatabase attachedDatabase;
  final String? _alias;
  RecurringPayments(this.attachedDatabase, [this._alias]);
  late final GeneratedColumn<String> id = GeneratedColumn<String>(
    'id',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<String> name = GeneratedColumn<String>(
    'name',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<int> amountMinor = GeneratedColumn<int>(
    'amount_minor',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<String> currencyCode = GeneratedColumn<String>(
    'currency_code',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<String> nextPaymentDate = GeneratedColumn<String>(
    'next_payment_date',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<int> billingDay = GeneratedColumn<int>(
    'billing_day',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<String> paymentMethodNickname =
      GeneratedColumn<String>(
        'payment_method_nickname',
        aliasedName,
        true,
        type: DriftSqlType.string,
        requiredDuringInsert: false,
        $customConstraints: 'NULL',
      );
  late final GeneratedColumn<String> category = GeneratedColumn<String>(
    'category',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<int> active = GeneratedColumn<int>(
    'active',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: false,
    $customConstraints: 'NOT NULL DEFAULT 1 CHECK (active IN (0, 1))',
    defaultValue: const CustomExpression('1'),
  );
  late final GeneratedColumn<int> createdAtUtc = GeneratedColumn<int>(
    'created_at_utc',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  @override
  List<GeneratedColumn> get $columns => [
    id,
    name,
    amountMinor,
    currencyCode,
    nextPaymentDate,
    billingDay,
    paymentMethodNickname,
    category,
    active,
    createdAtUtc,
  ];
  @override
  String get aliasedName => _alias ?? actualTableName;
  @override
  String get actualTableName => $name;
  static const String $name = 'recurring_payments';
  @override
  Set<GeneratedColumn> get $primaryKey => {id};
  @override
  RecurringPaymentsData map(Map<String, dynamic> data, {String? tablePrefix}) {
    final effectivePrefix = tablePrefix != null ? '$tablePrefix.' : '';
    return RecurringPaymentsData(
      id: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}id'],
      )!,
      name: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}name'],
      )!,
      amountMinor: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}amount_minor'],
      )!,
      currencyCode: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}currency_code'],
      )!,
      nextPaymentDate: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}next_payment_date'],
      )!,
      billingDay: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}billing_day'],
      )!,
      paymentMethodNickname: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}payment_method_nickname'],
      ),
      category: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}category'],
      )!,
      active: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}active'],
      )!,
      createdAtUtc: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}created_at_utc'],
      )!,
    );
  }

  @override
  RecurringPayments createAlias(String alias) {
    return RecurringPayments(attachedDatabase, alias);
  }

  @override
  List<String> get customConstraints => const ['PRIMARY KEY(id)'];
  @override
  bool get dontWriteConstraints => true;
}

class RecurringPaymentsData extends DataClass
    implements Insertable<RecurringPaymentsData> {
  final String id;
  final String name;
  final int amountMinor;
  final String currencyCode;
  final String nextPaymentDate;
  final int billingDay;
  final String? paymentMethodNickname;
  final String category;
  final int active;
  final int createdAtUtc;
  const RecurringPaymentsData({
    required this.id,
    required this.name,
    required this.amountMinor,
    required this.currencyCode,
    required this.nextPaymentDate,
    required this.billingDay,
    this.paymentMethodNickname,
    required this.category,
    required this.active,
    required this.createdAtUtc,
  });
  @override
  Map<String, Expression> toColumns(bool nullToAbsent) {
    final map = <String, Expression>{};
    map['id'] = Variable<String>(id);
    map['name'] = Variable<String>(name);
    map['amount_minor'] = Variable<int>(amountMinor);
    map['currency_code'] = Variable<String>(currencyCode);
    map['next_payment_date'] = Variable<String>(nextPaymentDate);
    map['billing_day'] = Variable<int>(billingDay);
    if (!nullToAbsent || paymentMethodNickname != null) {
      map['payment_method_nickname'] = Variable<String>(paymentMethodNickname);
    }
    map['category'] = Variable<String>(category);
    map['active'] = Variable<int>(active);
    map['created_at_utc'] = Variable<int>(createdAtUtc);
    return map;
  }

  RecurringPaymentsCompanion toCompanion(bool nullToAbsent) {
    return RecurringPaymentsCompanion(
      id: Value(id),
      name: Value(name),
      amountMinor: Value(amountMinor),
      currencyCode: Value(currencyCode),
      nextPaymentDate: Value(nextPaymentDate),
      billingDay: Value(billingDay),
      paymentMethodNickname: paymentMethodNickname == null && nullToAbsent
          ? const Value.absent()
          : Value(paymentMethodNickname),
      category: Value(category),
      active: Value(active),
      createdAtUtc: Value(createdAtUtc),
    );
  }

  factory RecurringPaymentsData.fromJson(
    Map<String, dynamic> json, {
    ValueSerializer? serializer,
  }) {
    serializer ??= driftRuntimeOptions.defaultSerializer;
    return RecurringPaymentsData(
      id: serializer.fromJson<String>(json['id']),
      name: serializer.fromJson<String>(json['name']),
      amountMinor: serializer.fromJson<int>(json['amountMinor']),
      currencyCode: serializer.fromJson<String>(json['currencyCode']),
      nextPaymentDate: serializer.fromJson<String>(json['nextPaymentDate']),
      billingDay: serializer.fromJson<int>(json['billingDay']),
      paymentMethodNickname: serializer.fromJson<String?>(
        json['paymentMethodNickname'],
      ),
      category: serializer.fromJson<String>(json['category']),
      active: serializer.fromJson<int>(json['active']),
      createdAtUtc: serializer.fromJson<int>(json['createdAtUtc']),
    );
  }
  @override
  Map<String, dynamic> toJson({ValueSerializer? serializer}) {
    serializer ??= driftRuntimeOptions.defaultSerializer;
    return <String, dynamic>{
      'id': serializer.toJson<String>(id),
      'name': serializer.toJson<String>(name),
      'amountMinor': serializer.toJson<int>(amountMinor),
      'currencyCode': serializer.toJson<String>(currencyCode),
      'nextPaymentDate': serializer.toJson<String>(nextPaymentDate),
      'billingDay': serializer.toJson<int>(billingDay),
      'paymentMethodNickname': serializer.toJson<String?>(
        paymentMethodNickname,
      ),
      'category': serializer.toJson<String>(category),
      'active': serializer.toJson<int>(active),
      'createdAtUtc': serializer.toJson<int>(createdAtUtc),
    };
  }

  RecurringPaymentsData copyWith({
    String? id,
    String? name,
    int? amountMinor,
    String? currencyCode,
    String? nextPaymentDate,
    int? billingDay,
    Value<String?> paymentMethodNickname = const Value.absent(),
    String? category,
    int? active,
    int? createdAtUtc,
  }) => RecurringPaymentsData(
    id: id ?? this.id,
    name: name ?? this.name,
    amountMinor: amountMinor ?? this.amountMinor,
    currencyCode: currencyCode ?? this.currencyCode,
    nextPaymentDate: nextPaymentDate ?? this.nextPaymentDate,
    billingDay: billingDay ?? this.billingDay,
    paymentMethodNickname: paymentMethodNickname.present
        ? paymentMethodNickname.value
        : this.paymentMethodNickname,
    category: category ?? this.category,
    active: active ?? this.active,
    createdAtUtc: createdAtUtc ?? this.createdAtUtc,
  );
  RecurringPaymentsData copyWithCompanion(RecurringPaymentsCompanion data) {
    return RecurringPaymentsData(
      id: data.id.present ? data.id.value : this.id,
      name: data.name.present ? data.name.value : this.name,
      amountMinor: data.amountMinor.present
          ? data.amountMinor.value
          : this.amountMinor,
      currencyCode: data.currencyCode.present
          ? data.currencyCode.value
          : this.currencyCode,
      nextPaymentDate: data.nextPaymentDate.present
          ? data.nextPaymentDate.value
          : this.nextPaymentDate,
      billingDay: data.billingDay.present
          ? data.billingDay.value
          : this.billingDay,
      paymentMethodNickname: data.paymentMethodNickname.present
          ? data.paymentMethodNickname.value
          : this.paymentMethodNickname,
      category: data.category.present ? data.category.value : this.category,
      active: data.active.present ? data.active.value : this.active,
      createdAtUtc: data.createdAtUtc.present
          ? data.createdAtUtc.value
          : this.createdAtUtc,
    );
  }

  @override
  String toString() {
    return (StringBuffer('RecurringPaymentsData(')
          ..write('id: $id, ')
          ..write('name: $name, ')
          ..write('amountMinor: $amountMinor, ')
          ..write('currencyCode: $currencyCode, ')
          ..write('nextPaymentDate: $nextPaymentDate, ')
          ..write('billingDay: $billingDay, ')
          ..write('paymentMethodNickname: $paymentMethodNickname, ')
          ..write('category: $category, ')
          ..write('active: $active, ')
          ..write('createdAtUtc: $createdAtUtc')
          ..write(')'))
        .toString();
  }

  @override
  int get hashCode => Object.hash(
    id,
    name,
    amountMinor,
    currencyCode,
    nextPaymentDate,
    billingDay,
    paymentMethodNickname,
    category,
    active,
    createdAtUtc,
  );
  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      (other is RecurringPaymentsData &&
          other.id == this.id &&
          other.name == this.name &&
          other.amountMinor == this.amountMinor &&
          other.currencyCode == this.currencyCode &&
          other.nextPaymentDate == this.nextPaymentDate &&
          other.billingDay == this.billingDay &&
          other.paymentMethodNickname == this.paymentMethodNickname &&
          other.category == this.category &&
          other.active == this.active &&
          other.createdAtUtc == this.createdAtUtc);
}

class RecurringPaymentsCompanion
    extends UpdateCompanion<RecurringPaymentsData> {
  final Value<String> id;
  final Value<String> name;
  final Value<int> amountMinor;
  final Value<String> currencyCode;
  final Value<String> nextPaymentDate;
  final Value<int> billingDay;
  final Value<String?> paymentMethodNickname;
  final Value<String> category;
  final Value<int> active;
  final Value<int> createdAtUtc;
  final Value<int> rowid;
  const RecurringPaymentsCompanion({
    this.id = const Value.absent(),
    this.name = const Value.absent(),
    this.amountMinor = const Value.absent(),
    this.currencyCode = const Value.absent(),
    this.nextPaymentDate = const Value.absent(),
    this.billingDay = const Value.absent(),
    this.paymentMethodNickname = const Value.absent(),
    this.category = const Value.absent(),
    this.active = const Value.absent(),
    this.createdAtUtc = const Value.absent(),
    this.rowid = const Value.absent(),
  });
  RecurringPaymentsCompanion.insert({
    required String id,
    required String name,
    required int amountMinor,
    required String currencyCode,
    required String nextPaymentDate,
    required int billingDay,
    this.paymentMethodNickname = const Value.absent(),
    required String category,
    this.active = const Value.absent(),
    required int createdAtUtc,
    this.rowid = const Value.absent(),
  }) : id = Value(id),
       name = Value(name),
       amountMinor = Value(amountMinor),
       currencyCode = Value(currencyCode),
       nextPaymentDate = Value(nextPaymentDate),
       billingDay = Value(billingDay),
       category = Value(category),
       createdAtUtc = Value(createdAtUtc);
  static Insertable<RecurringPaymentsData> custom({
    Expression<String>? id,
    Expression<String>? name,
    Expression<int>? amountMinor,
    Expression<String>? currencyCode,
    Expression<String>? nextPaymentDate,
    Expression<int>? billingDay,
    Expression<String>? paymentMethodNickname,
    Expression<String>? category,
    Expression<int>? active,
    Expression<int>? createdAtUtc,
    Expression<int>? rowid,
  }) {
    return RawValuesInsertable({
      if (id != null) 'id': id,
      if (name != null) 'name': name,
      if (amountMinor != null) 'amount_minor': amountMinor,
      if (currencyCode != null) 'currency_code': currencyCode,
      if (nextPaymentDate != null) 'next_payment_date': nextPaymentDate,
      if (billingDay != null) 'billing_day': billingDay,
      if (paymentMethodNickname != null)
        'payment_method_nickname': paymentMethodNickname,
      if (category != null) 'category': category,
      if (active != null) 'active': active,
      if (createdAtUtc != null) 'created_at_utc': createdAtUtc,
      if (rowid != null) 'rowid': rowid,
    });
  }

  RecurringPaymentsCompanion copyWith({
    Value<String>? id,
    Value<String>? name,
    Value<int>? amountMinor,
    Value<String>? currencyCode,
    Value<String>? nextPaymentDate,
    Value<int>? billingDay,
    Value<String?>? paymentMethodNickname,
    Value<String>? category,
    Value<int>? active,
    Value<int>? createdAtUtc,
    Value<int>? rowid,
  }) {
    return RecurringPaymentsCompanion(
      id: id ?? this.id,
      name: name ?? this.name,
      amountMinor: amountMinor ?? this.amountMinor,
      currencyCode: currencyCode ?? this.currencyCode,
      nextPaymentDate: nextPaymentDate ?? this.nextPaymentDate,
      billingDay: billingDay ?? this.billingDay,
      paymentMethodNickname:
          paymentMethodNickname ?? this.paymentMethodNickname,
      category: category ?? this.category,
      active: active ?? this.active,
      createdAtUtc: createdAtUtc ?? this.createdAtUtc,
      rowid: rowid ?? this.rowid,
    );
  }

  @override
  Map<String, Expression> toColumns(bool nullToAbsent) {
    final map = <String, Expression>{};
    if (id.present) {
      map['id'] = Variable<String>(id.value);
    }
    if (name.present) {
      map['name'] = Variable<String>(name.value);
    }
    if (amountMinor.present) {
      map['amount_minor'] = Variable<int>(amountMinor.value);
    }
    if (currencyCode.present) {
      map['currency_code'] = Variable<String>(currencyCode.value);
    }
    if (nextPaymentDate.present) {
      map['next_payment_date'] = Variable<String>(nextPaymentDate.value);
    }
    if (billingDay.present) {
      map['billing_day'] = Variable<int>(billingDay.value);
    }
    if (paymentMethodNickname.present) {
      map['payment_method_nickname'] = Variable<String>(
        paymentMethodNickname.value,
      );
    }
    if (category.present) {
      map['category'] = Variable<String>(category.value);
    }
    if (active.present) {
      map['active'] = Variable<int>(active.value);
    }
    if (createdAtUtc.present) {
      map['created_at_utc'] = Variable<int>(createdAtUtc.value);
    }
    if (rowid.present) {
      map['rowid'] = Variable<int>(rowid.value);
    }
    return map;
  }

  @override
  String toString() {
    return (StringBuffer('RecurringPaymentsCompanion(')
          ..write('id: $id, ')
          ..write('name: $name, ')
          ..write('amountMinor: $amountMinor, ')
          ..write('currencyCode: $currencyCode, ')
          ..write('nextPaymentDate: $nextPaymentDate, ')
          ..write('billingDay: $billingDay, ')
          ..write('paymentMethodNickname: $paymentMethodNickname, ')
          ..write('category: $category, ')
          ..write('active: $active, ')
          ..write('createdAtUtc: $createdAtUtc, ')
          ..write('rowid: $rowid')
          ..write(')'))
        .toString();
  }
}

class PaymentOccurrences extends Table
    with TableInfo<PaymentOccurrences, PaymentOccurrencesData> {
  @override
  final GeneratedDatabase attachedDatabase;
  final String? _alias;
  PaymentOccurrences(this.attachedDatabase, [this._alias]);
  late final GeneratedColumn<String> id = GeneratedColumn<String>(
    'id',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<String> recurringPaymentId =
      GeneratedColumn<String>(
        'recurring_payment_id',
        aliasedName,
        false,
        type: DriftSqlType.string,
        requiredDuringInsert: true,
        $customConstraints: 'NOT NULL REFERENCES recurring_payments(id)',
      );
  late final GeneratedColumn<String> paymentName = GeneratedColumn<String>(
    'payment_name',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<String> expectedDate = GeneratedColumn<String>(
    'expected_date',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<int> expectedAmountMinor = GeneratedColumn<int>(
    'expected_amount_minor',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<String> currencyCode = GeneratedColumn<String>(
    'currency_code',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<String> status = GeneratedColumn<String>(
    'status',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<int> actualAmountMinor = GeneratedColumn<int>(
    'actual_amount_minor',
    aliasedName,
    true,
    type: DriftSqlType.int,
    requiredDuringInsert: false,
    $customConstraints: 'NULL',
  );
  late final GeneratedColumn<int> confirmedAtUtc = GeneratedColumn<int>(
    'confirmed_at_utc',
    aliasedName,
    true,
    type: DriftSqlType.int,
    requiredDuringInsert: false,
    $customConstraints: 'NULL',
  );
  @override
  List<GeneratedColumn> get $columns => [
    id,
    recurringPaymentId,
    paymentName,
    expectedDate,
    expectedAmountMinor,
    currencyCode,
    status,
    actualAmountMinor,
    confirmedAtUtc,
  ];
  @override
  String get aliasedName => _alias ?? actualTableName;
  @override
  String get actualTableName => $name;
  static const String $name = 'payment_occurrences';
  @override
  Set<GeneratedColumn> get $primaryKey => {id};
  @override
  List<Set<GeneratedColumn>> get uniqueKeys => [
    {recurringPaymentId, expectedDate},
  ];
  @override
  PaymentOccurrencesData map(Map<String, dynamic> data, {String? tablePrefix}) {
    final effectivePrefix = tablePrefix != null ? '$tablePrefix.' : '';
    return PaymentOccurrencesData(
      id: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}id'],
      )!,
      recurringPaymentId: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}recurring_payment_id'],
      )!,
      paymentName: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}payment_name'],
      )!,
      expectedDate: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}expected_date'],
      )!,
      expectedAmountMinor: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}expected_amount_minor'],
      )!,
      currencyCode: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}currency_code'],
      )!,
      status: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}status'],
      )!,
      actualAmountMinor: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}actual_amount_minor'],
      ),
      confirmedAtUtc: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}confirmed_at_utc'],
      ),
    );
  }

  @override
  PaymentOccurrences createAlias(String alias) {
    return PaymentOccurrences(attachedDatabase, alias);
  }

  @override
  List<String> get customConstraints => const [
    'PRIMARY KEY(id)',
    'UNIQUE(recurring_payment_id, expected_date)',
  ];
  @override
  bool get dontWriteConstraints => true;
}

class PaymentOccurrencesData extends DataClass
    implements Insertable<PaymentOccurrencesData> {
  final String id;
  final String recurringPaymentId;
  final String paymentName;
  final String expectedDate;
  final int expectedAmountMinor;
  final String currencyCode;
  final String status;
  final int? actualAmountMinor;
  final int? confirmedAtUtc;
  const PaymentOccurrencesData({
    required this.id,
    required this.recurringPaymentId,
    required this.paymentName,
    required this.expectedDate,
    required this.expectedAmountMinor,
    required this.currencyCode,
    required this.status,
    this.actualAmountMinor,
    this.confirmedAtUtc,
  });
  @override
  Map<String, Expression> toColumns(bool nullToAbsent) {
    final map = <String, Expression>{};
    map['id'] = Variable<String>(id);
    map['recurring_payment_id'] = Variable<String>(recurringPaymentId);
    map['payment_name'] = Variable<String>(paymentName);
    map['expected_date'] = Variable<String>(expectedDate);
    map['expected_amount_minor'] = Variable<int>(expectedAmountMinor);
    map['currency_code'] = Variable<String>(currencyCode);
    map['status'] = Variable<String>(status);
    if (!nullToAbsent || actualAmountMinor != null) {
      map['actual_amount_minor'] = Variable<int>(actualAmountMinor);
    }
    if (!nullToAbsent || confirmedAtUtc != null) {
      map['confirmed_at_utc'] = Variable<int>(confirmedAtUtc);
    }
    return map;
  }

  PaymentOccurrencesCompanion toCompanion(bool nullToAbsent) {
    return PaymentOccurrencesCompanion(
      id: Value(id),
      recurringPaymentId: Value(recurringPaymentId),
      paymentName: Value(paymentName),
      expectedDate: Value(expectedDate),
      expectedAmountMinor: Value(expectedAmountMinor),
      currencyCode: Value(currencyCode),
      status: Value(status),
      actualAmountMinor: actualAmountMinor == null && nullToAbsent
          ? const Value.absent()
          : Value(actualAmountMinor),
      confirmedAtUtc: confirmedAtUtc == null && nullToAbsent
          ? const Value.absent()
          : Value(confirmedAtUtc),
    );
  }

  factory PaymentOccurrencesData.fromJson(
    Map<String, dynamic> json, {
    ValueSerializer? serializer,
  }) {
    serializer ??= driftRuntimeOptions.defaultSerializer;
    return PaymentOccurrencesData(
      id: serializer.fromJson<String>(json['id']),
      recurringPaymentId: serializer.fromJson<String>(
        json['recurringPaymentId'],
      ),
      paymentName: serializer.fromJson<String>(json['paymentName']),
      expectedDate: serializer.fromJson<String>(json['expectedDate']),
      expectedAmountMinor: serializer.fromJson<int>(
        json['expectedAmountMinor'],
      ),
      currencyCode: serializer.fromJson<String>(json['currencyCode']),
      status: serializer.fromJson<String>(json['status']),
      actualAmountMinor: serializer.fromJson<int?>(json['actualAmountMinor']),
      confirmedAtUtc: serializer.fromJson<int?>(json['confirmedAtUtc']),
    );
  }
  @override
  Map<String, dynamic> toJson({ValueSerializer? serializer}) {
    serializer ??= driftRuntimeOptions.defaultSerializer;
    return <String, dynamic>{
      'id': serializer.toJson<String>(id),
      'recurringPaymentId': serializer.toJson<String>(recurringPaymentId),
      'paymentName': serializer.toJson<String>(paymentName),
      'expectedDate': serializer.toJson<String>(expectedDate),
      'expectedAmountMinor': serializer.toJson<int>(expectedAmountMinor),
      'currencyCode': serializer.toJson<String>(currencyCode),
      'status': serializer.toJson<String>(status),
      'actualAmountMinor': serializer.toJson<int?>(actualAmountMinor),
      'confirmedAtUtc': serializer.toJson<int?>(confirmedAtUtc),
    };
  }

  PaymentOccurrencesData copyWith({
    String? id,
    String? recurringPaymentId,
    String? paymentName,
    String? expectedDate,
    int? expectedAmountMinor,
    String? currencyCode,
    String? status,
    Value<int?> actualAmountMinor = const Value.absent(),
    Value<int?> confirmedAtUtc = const Value.absent(),
  }) => PaymentOccurrencesData(
    id: id ?? this.id,
    recurringPaymentId: recurringPaymentId ?? this.recurringPaymentId,
    paymentName: paymentName ?? this.paymentName,
    expectedDate: expectedDate ?? this.expectedDate,
    expectedAmountMinor: expectedAmountMinor ?? this.expectedAmountMinor,
    currencyCode: currencyCode ?? this.currencyCode,
    status: status ?? this.status,
    actualAmountMinor: actualAmountMinor.present
        ? actualAmountMinor.value
        : this.actualAmountMinor,
    confirmedAtUtc: confirmedAtUtc.present
        ? confirmedAtUtc.value
        : this.confirmedAtUtc,
  );
  PaymentOccurrencesData copyWithCompanion(PaymentOccurrencesCompanion data) {
    return PaymentOccurrencesData(
      id: data.id.present ? data.id.value : this.id,
      recurringPaymentId: data.recurringPaymentId.present
          ? data.recurringPaymentId.value
          : this.recurringPaymentId,
      paymentName: data.paymentName.present
          ? data.paymentName.value
          : this.paymentName,
      expectedDate: data.expectedDate.present
          ? data.expectedDate.value
          : this.expectedDate,
      expectedAmountMinor: data.expectedAmountMinor.present
          ? data.expectedAmountMinor.value
          : this.expectedAmountMinor,
      currencyCode: data.currencyCode.present
          ? data.currencyCode.value
          : this.currencyCode,
      status: data.status.present ? data.status.value : this.status,
      actualAmountMinor: data.actualAmountMinor.present
          ? data.actualAmountMinor.value
          : this.actualAmountMinor,
      confirmedAtUtc: data.confirmedAtUtc.present
          ? data.confirmedAtUtc.value
          : this.confirmedAtUtc,
    );
  }

  @override
  String toString() {
    return (StringBuffer('PaymentOccurrencesData(')
          ..write('id: $id, ')
          ..write('recurringPaymentId: $recurringPaymentId, ')
          ..write('paymentName: $paymentName, ')
          ..write('expectedDate: $expectedDate, ')
          ..write('expectedAmountMinor: $expectedAmountMinor, ')
          ..write('currencyCode: $currencyCode, ')
          ..write('status: $status, ')
          ..write('actualAmountMinor: $actualAmountMinor, ')
          ..write('confirmedAtUtc: $confirmedAtUtc')
          ..write(')'))
        .toString();
  }

  @override
  int get hashCode => Object.hash(
    id,
    recurringPaymentId,
    paymentName,
    expectedDate,
    expectedAmountMinor,
    currencyCode,
    status,
    actualAmountMinor,
    confirmedAtUtc,
  );
  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      (other is PaymentOccurrencesData &&
          other.id == this.id &&
          other.recurringPaymentId == this.recurringPaymentId &&
          other.paymentName == this.paymentName &&
          other.expectedDate == this.expectedDate &&
          other.expectedAmountMinor == this.expectedAmountMinor &&
          other.currencyCode == this.currencyCode &&
          other.status == this.status &&
          other.actualAmountMinor == this.actualAmountMinor &&
          other.confirmedAtUtc == this.confirmedAtUtc);
}

class PaymentOccurrencesCompanion
    extends UpdateCompanion<PaymentOccurrencesData> {
  final Value<String> id;
  final Value<String> recurringPaymentId;
  final Value<String> paymentName;
  final Value<String> expectedDate;
  final Value<int> expectedAmountMinor;
  final Value<String> currencyCode;
  final Value<String> status;
  final Value<int?> actualAmountMinor;
  final Value<int?> confirmedAtUtc;
  final Value<int> rowid;
  const PaymentOccurrencesCompanion({
    this.id = const Value.absent(),
    this.recurringPaymentId = const Value.absent(),
    this.paymentName = const Value.absent(),
    this.expectedDate = const Value.absent(),
    this.expectedAmountMinor = const Value.absent(),
    this.currencyCode = const Value.absent(),
    this.status = const Value.absent(),
    this.actualAmountMinor = const Value.absent(),
    this.confirmedAtUtc = const Value.absent(),
    this.rowid = const Value.absent(),
  });
  PaymentOccurrencesCompanion.insert({
    required String id,
    required String recurringPaymentId,
    required String paymentName,
    required String expectedDate,
    required int expectedAmountMinor,
    required String currencyCode,
    required String status,
    this.actualAmountMinor = const Value.absent(),
    this.confirmedAtUtc = const Value.absent(),
    this.rowid = const Value.absent(),
  }) : id = Value(id),
       recurringPaymentId = Value(recurringPaymentId),
       paymentName = Value(paymentName),
       expectedDate = Value(expectedDate),
       expectedAmountMinor = Value(expectedAmountMinor),
       currencyCode = Value(currencyCode),
       status = Value(status);
  static Insertable<PaymentOccurrencesData> custom({
    Expression<String>? id,
    Expression<String>? recurringPaymentId,
    Expression<String>? paymentName,
    Expression<String>? expectedDate,
    Expression<int>? expectedAmountMinor,
    Expression<String>? currencyCode,
    Expression<String>? status,
    Expression<int>? actualAmountMinor,
    Expression<int>? confirmedAtUtc,
    Expression<int>? rowid,
  }) {
    return RawValuesInsertable({
      if (id != null) 'id': id,
      if (recurringPaymentId != null)
        'recurring_payment_id': recurringPaymentId,
      if (paymentName != null) 'payment_name': paymentName,
      if (expectedDate != null) 'expected_date': expectedDate,
      if (expectedAmountMinor != null)
        'expected_amount_minor': expectedAmountMinor,
      if (currencyCode != null) 'currency_code': currencyCode,
      if (status != null) 'status': status,
      if (actualAmountMinor != null) 'actual_amount_minor': actualAmountMinor,
      if (confirmedAtUtc != null) 'confirmed_at_utc': confirmedAtUtc,
      if (rowid != null) 'rowid': rowid,
    });
  }

  PaymentOccurrencesCompanion copyWith({
    Value<String>? id,
    Value<String>? recurringPaymentId,
    Value<String>? paymentName,
    Value<String>? expectedDate,
    Value<int>? expectedAmountMinor,
    Value<String>? currencyCode,
    Value<String>? status,
    Value<int?>? actualAmountMinor,
    Value<int?>? confirmedAtUtc,
    Value<int>? rowid,
  }) {
    return PaymentOccurrencesCompanion(
      id: id ?? this.id,
      recurringPaymentId: recurringPaymentId ?? this.recurringPaymentId,
      paymentName: paymentName ?? this.paymentName,
      expectedDate: expectedDate ?? this.expectedDate,
      expectedAmountMinor: expectedAmountMinor ?? this.expectedAmountMinor,
      currencyCode: currencyCode ?? this.currencyCode,
      status: status ?? this.status,
      actualAmountMinor: actualAmountMinor ?? this.actualAmountMinor,
      confirmedAtUtc: confirmedAtUtc ?? this.confirmedAtUtc,
      rowid: rowid ?? this.rowid,
    );
  }

  @override
  Map<String, Expression> toColumns(bool nullToAbsent) {
    final map = <String, Expression>{};
    if (id.present) {
      map['id'] = Variable<String>(id.value);
    }
    if (recurringPaymentId.present) {
      map['recurring_payment_id'] = Variable<String>(recurringPaymentId.value);
    }
    if (paymentName.present) {
      map['payment_name'] = Variable<String>(paymentName.value);
    }
    if (expectedDate.present) {
      map['expected_date'] = Variable<String>(expectedDate.value);
    }
    if (expectedAmountMinor.present) {
      map['expected_amount_minor'] = Variable<int>(expectedAmountMinor.value);
    }
    if (currencyCode.present) {
      map['currency_code'] = Variable<String>(currencyCode.value);
    }
    if (status.present) {
      map['status'] = Variable<String>(status.value);
    }
    if (actualAmountMinor.present) {
      map['actual_amount_minor'] = Variable<int>(actualAmountMinor.value);
    }
    if (confirmedAtUtc.present) {
      map['confirmed_at_utc'] = Variable<int>(confirmedAtUtc.value);
    }
    if (rowid.present) {
      map['rowid'] = Variable<int>(rowid.value);
    }
    return map;
  }

  @override
  String toString() {
    return (StringBuffer('PaymentOccurrencesCompanion(')
          ..write('id: $id, ')
          ..write('recurringPaymentId: $recurringPaymentId, ')
          ..write('paymentName: $paymentName, ')
          ..write('expectedDate: $expectedDate, ')
          ..write('expectedAmountMinor: $expectedAmountMinor, ')
          ..write('currencyCode: $currencyCode, ')
          ..write('status: $status, ')
          ..write('actualAmountMinor: $actualAmountMinor, ')
          ..write('confirmedAtUtc: $confirmedAtUtc, ')
          ..write('rowid: $rowid')
          ..write(')'))
        .toString();
  }
}

class DatabaseAtV1 extends GeneratedDatabase {
  DatabaseAtV1(QueryExecutor e) : super(e);
  late final RecurringPayments recurringPayments = RecurringPayments(this);
  late final PaymentOccurrences paymentOccurrences = PaymentOccurrences(this);
  @override
  Iterable<TableInfo<Table, Object?>> get allTables =>
      allSchemaEntities.whereType<TableInfo<Table, Object?>>();
  @override
  List<DatabaseSchemaEntity> get allSchemaEntities => [
    recurringPayments,
    paymentOccurrences,
  ];
  @override
  int get schemaVersion => 1;
}
